books/book_data/urls.py
from django.urls import path
from .views import (
    book_details, chapter_form, create_sub_section,
    delete_book, delete_chapter, delete_subsection, edit_book, home, create_book,
    delete_book, books_by_author, create_heading, login_view, logout_view, signup
)


urlpatterns = [
    path('', home, name="home"),
    path('create_book/', create_book, name="create_book"),
    path('delete_book/<int:id>/', delete_book, name="delete_book"),
    path('edit_book/<int:id>/', edit_book, name="edit_book"),
    path('book/<int:id>/', book_details, name="book_details"),
    path('books_by_author/<int:id>/', books_by_author, name="books_by_author"),
    path('chapter_form/<int:bookid>/', chapter_form, name="chapter_form"),
    path('create_sub_section/<int:sectionid>/<int:bootid>/',
         create_sub_section, name="create_sub_section"),
    path('create_heading/<int:chapterid>/<int:bootid>/',
         create_heading, name="create_heading"),
    path('delete_chapter/<int:id>/<int:bookid>/',
         delete_chapter, name="delete_chapter"),
    path('delete_subsection/<int:id>/<int:bookid>/',
         delete_subsection, name="delete_subsection"),
    path('logout_view/ ',
         logout_view, name="logout_view"),
    path('login_view/ ',
         login_view, name="login_view"),
    path('signup/ ',
         signup, name="signup"),
]

books/books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),

    path("", include('book_data.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/book_data/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
# Create your models here.

# getting User model 
User = get_user_model()


class Book(models.Model):
    """This model is use to manage books."""
    name = models.CharField(max_length=100)
    cover = models.ImageField(upload_to='cover', blank=True, null=True)
    author_name = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        """Meta definition for Book."""

        verbose_name = 'Book'
        verbose_name_plural = 'Books'

    def __str__(self):
        """String representation of Book."""
        return f'{self.name}'

    def get_delete_url(self):
        return reverse('delete_book', kwargs={'id': self.pk})


class Chapter(models.Model):
    """Model to deal with multiple chapters in one book."""

    book_name = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_no = models.FloatField()
    chapter_name = models.CharField(max_length=100)

    class Meta:
        """Meta definition for Chapter."""

        verbose_name = 'Chapter'
        verbose_name_plural = 'Chapters'

    def __str__(self):
        """String representation of Chapter."""
        return f'{self.chapter_name}'


class Section(models.Model):

    name = models.CharField(max_length=100)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, blank=True, null=True)
    super_section = models.ForeignKey('self',on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Section'
        verbose_name_plural = 'Sections'

books/book_data/forms.py
from django import forms
from croppie.fields import CroppieField

from .models import Book, Chapter, Section

class BookForm(forms.ModelForm):
    cover = CroppieField(
        options={
            'viewport': {
                'width': 300,
                'height': 450,
            },
            'boundary': {
                'width': 325,
                'height': 475
            },
            'showZoomer': True,
        },
        required=False
    )
    class Meta:
        model = Book
        fields = ('name','cover')

class ChapterForm(forms.ModelForm):
    
    class Meta:
        model = Chapter
        fields = ("chapter_no",'chapter_name')

class SectionForm(forms.ModelForm):

    class Meta:

        model = Section
        fields = ('name','description')

books/book_data/views.py
from unicodedata import name
from django.urls import reverse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import get_user_model
from .forms import BookForm, ChapterForm, SectionForm
from .models import Book, Chapter, Section
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm


def home(request):
    if request.method == 'POST':
        search = request.POST.get('search')
        books = Book.objects.select_related('author_name').filter(name__startswith=search)
    else:
        books = Book.objects.select_related('author_name').all()
    context = {
        'books': books,
        'title': 'ALL BOOK'
    }
    return render(request, 'book_data/home.html', context)


def create_book(request):
    form = BookForm(request.POST, request.FILES or None)
    if form.is_valid():
        book = form.save(commit=False)
        book.author_name = request.user
        book.save()
        form = BookForm()

    context = {'form': form}
    return render(request, 'book_data/book_form.html', context)


def edit_book(request, id):
    bookobj = Book.objects.get(id=id)
    if request.user == bookobj.author_name:
        if request.method == 'POST':
            form = BookForm(request.POST, request.FILES, instance=bookobj)
            if form.is_valid():
                book = form.save(commit=False)
                book.author_name = request.user
                book.save()
                messages.add_message(
                    request, messages.SUCCESS, f"Book has been updated successfully")
                return redirect('home')
        form = BookForm(instance=bookobj)
        context = {'form': form}
        return render(request, 'book_data/book_form.html', context)
    else:
        messages.add_message(request, messages.WARNING,
                             f"You don't have permissions to change this {bookobj.name}")
    return redirect('home')


def books_by_author(request, id):
    try:
        books = Book.objects.select_related(
            'author_name').filter(author_name__id=id)
        context = {
            'books': books,
            'title': f'ALL BOOK OF {str(books.last().author_name.username).upper()}'

        }
    except:
        context = {
            'title':'Author do not have any book yet'
        }
    return render(request, 'book_data/home.html', context)


def delete_book(request, id):
    book = Book.objects.get(id=id)
    if request.user == book.author_name:
        book.delete()
        messages.add_message(request, messages.SUCCESS,
                             f"  Your book {book.name} has been deleted successfully")
    else:
        messages.add_message(request, messages.WARNING,
                             f"You don't have permissions to delete this {book.name}")
    return redirect('home')


def book_details(request, id):
    book = Book.objects.prefetch_related(
        'chapter_set', 'chapter_set__section_set__section_set__section_set__section_set__section_set__section_set__section_set__section_set__section_set__section_set__section_set').select_related('author_name').get(id=id)

    context = {
        'book': book,
    }
    return render(request, 'book_data/book_details.html', context)


def chapter_form(request, **kwargs):
    form = ChapterForm()
    book_id = kwargs.get('bookid')
    book = Book.objects.get(id=book_id)
    if request.method == "POST":
        form = ChapterForm(request.POST)
        if form.is_valid():
            chapter = form.save(commit=False)
            chapter.book_name = book
            chapter.save()
            return redirect(reverse('book_details', kwargs={'id': book_id}))
    context = {'form': form, 'BOOK_id': book_id}
    return render(request, 'book_data/chapter_form.html', context)


def create_sub_section(request, **kwargs):
    section_id = kwargs.get('sectionid')
    book_id = kwargs.get('bootid')
    section = Section.objects.get(id=section_id)
    form = SectionForm()
    if request.method == "POST":
        form = SectionForm(request.POST)
        if form.is_valid():
            new_section = form.save(commit=False)
            new_section.super_section = section
            new_section.save()
            return redirect(reverse('book_details', kwargs={'id': book_id}))

    context = {
        'section_id': section_id,
        'book_id': book_id,

        'form': form
    }
    return render(request, 'book_data/section_form.html', context)


def create_heading(request, **kwargs):
    chapter_id = kwargs.get('chapterid')
    book_id = kwargs.get('bootid')
    chapter = Chapter.objects.get(id=chapter_id)

    form = SectionForm()
    if request.method == "POST":
        form = SectionForm(request.POST)
        if form.is_valid():
            section = form.save(commit=False)
            section.chapter = chapter
            section.save()
            return redirect(reverse('book_details', kwargs={'id': book_id}))
    context = {
        'chapter_id': chapter_id,
        'book_id': book_id,
        'form': form
    }
    return render(request, 'book_data/heading_form.html', context)


def delete_chapter(request, id, bookid):
    chapter = Chapter.objects.get(id=id)
    chapter.delete()
    messages.add_message(request, messages.SUCCESS,
                         f"Your chapter {chapter.chapter_name} has been deleted successfully")

    return redirect(reverse('book_details', kwargs={'id': bookid}))


def delete_subsection(request, id, bookid):
    Sub_Section = Section.objects.get(id=id)
    Sub_Section.delete()
    messages.add_message(request, messages.SUCCESS,
                         f"Your Sub Section {Sub_Section.name} has been deleted successfully")

    return redirect(reverse('book_details', kwargs={'id': bookid}))


# we can use Django all auth but the nature
# of project was simple so
# use functional base aproach

def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        messages.add_message(request, messages.SUCCESS,
                             f"You are logged out successfully")
    else:
        messages.add_message(request, messages.WARNING,
                             f"You are allready logged out")
    return redirect('home')

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')


        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.add_message(request, messages.SUCCESS,
                                f"You are logged in successfully")
            return redirect('home')
        else:
            messages.add_message(request, messages.WARNING,
                                f"Your username or password are not correct")
    return render(request, 'book_data/login_form.html')



def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'book_data/signup.html', {'form': form})

books/book_data/templates/book_data/includes/book_card.html
<div class="col mb-4">
  <div class="card" style="width: 400px">
    <img
      class="card-img-top"
      src="{{book.cover.url}}"
      alt="Card image"
      style="width: 100%"
    />
    <div class="card-body">
      <h4 class="card-title">{{book.name}}</h4>
      <div class="row">
        <div class="col-12 mb-2">
          <button
            hx-get="{% url 'books_by_author' book.author_name.id %}"
            hx-push-url="{% url 'books_by_author' book.author_name.id %}"
            hx-target="#content"
            type="button"
            class="btn btn-success btn-sm"
          >
            {{book.author_name}}
          </button>
        </div>
        <div class="col-12">
          <button
            hx-get="{% url 'book_details' book.id %}"
            hx-push-url="{% url 'book_details' book.id %}"
            hx-target="#content"
            class="btn btn-primary"
          >
            Read Book
          </button>
          {% if request.user == book.author_name %}
          <button
            hx-get="{% url 'edit_book' book.id %}"
            hx-push-url="{% url 'edit_book' book.id %}"
            hx-target="#content"
            class="btn btn-warning"
          >
            Edit Book
          </button>
          <button
            hx-confirm="Do you really want to delete {{ book.name }}"
            hx-get="{{book.get_delete_url}}"
            hx-target="#content"
            class="btn btn-danger"
          >
            Delete Book
          </button>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

books/book_data/templates/book_data/includes/book_chapter_list.html
<div class="row">
  <div class="col-12">
    <h2 class="text-center">Chapters list</h2>
  </div>
  <div class="col-12">
    <table class="table table-striped">
      <thead class="thead-inverse">
        <tr>
          <th>Chapter No</th>
          <th>Chapter Name</th>
        </tr>
      </thead>
      <tbody >
        {% for chapter in book.chapter_set.all %}
        <tr>
          <td scope="row">{{chapter.chapter_no}}</td>
          <td>{{chapter.chapter_name }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="col-12 d-flex justify-content-center">
    <button
      type="button"
      hx-get="{% url 'chapter_form' book.id %}"
      hx-target=".modal-body"
      class="btn btn-primary btn-lg align-center"
      data-toggle="modal" data-target="#chaptermodel"
    >
      Add Chapter
    </button>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="chaptermodel" tabindex="-1" role="dialog" aria-labelledby="chaptermodel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add/Modify Chapter</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body" >
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

books/book_data/templates/book_data/includes/navbar.html
<!-- I am not using smentic html here to complete my task quickly -->

<div class="row bg-secondary p-3 rounded w-100">
  <div class="col-3">
    <a hx-get="{% url 'home' %}" hx-push-url="{% url 'home' %}"  hx-target="#content" ><h3 class="text-white">Khan Book Library</h3></a>
  </div>
  <div class="col-5">
    <form hx-post='{% url "home" %}'  hx-target="#content" class="d-flex">
      {% csrf_token %}
      <input
        class="form-control me-2 form-control-lg"
        type="search"
        name="search"
        placeholder="Search Book"
        aria-label="Search"
      />
      <button type="submit" class="btn btn-primary">search</button>
    </form>
  </div>

  {% if request.user.is_authenticated %}
  <div class="col-4">
    <div class="btn-group" role="group" aria-label="register">
      <button hx-get="{% url 'create_book' %}" hx-push-url="{% url 'create_book' %}" hx-target="#content" type="button" class="btn btn-primary btn-lg">Add Books</button>
      <button hx-get="{% url 'books_by_author' request.user.id %}" hx-push-url="{% url 'books_by_author' request.user.id %}" hx-target="#content" type="button" class="btn btn-success btn-lg">My Books</button>
      <a type="button" href="{% url 'logout_view' %}" class="btn btn-danger btn-lg">Log Out</a>
    </div>
  </div>
  {% else %}
  <div class="col-4">
    <div class="row">
      <div class="col-2"></div>
      <div class="col-10">
        <div class="btn-group" role="group" aria-label="register">
          <a type="button" href="{% url 'login_view' %}" class="btn btn-warning btn-lg">Login</a>
          <a type="button" href="{% url 'signup' %}" class="btn btn-danger btn-lg">Sign Up</a>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
</div>

books/book_data/templates/book_data/includes/section.html
{% for section in section.section_set.all %}

<div class="col-12">
    <div class="row text-left">
      <div class="col-10">
        <h3>{{section.name}}</h3>
      </div>
      {% if request.user == book.author_name %}

      <div class="col-2">
        <button
          type="button"
          hx-get="{% url 'create_sub_section' section.id book.id %}"
          hx-target=".modal-body"
          data-toggle="modal"
          data-target="#chaptermodel"
          class="btn btn-info btn-sm"
        >
          Add SubSection
        </button>
        <button
          type="button"
          hx-get="{% url 'delete_subsection' section.id book.id %}"
          hx-target="#content"
          hx-confirm="Do you really want to delete this sub section"
          class="btn btn-danger btn-sm my-2"
        >
          Delete SubSection
        </button>
        
      </div>
      {% endif %}
      <div class="col-12">
        <p>{{section.description}}</p>
        {% if section.section_set.all %}
        {% include 'book_data/includes/section.html' %}
        {% endif %}
      </div>
    </div>
</div>
    {% endfor %}